//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShootNBunny
{
    using System;
    using System.Collections.Generic;
    
    public partial class Complaint
    {
        public int ID { get; set; }
        public int ReasonID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> AuthorID { get; set; }
        public Nullable<int> ReviewID { get; set; }
        public Nullable<int> BookID { get; set; }
        public string Comment { get; set; }
        public bool Satisfied { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual Reason Reason { get; set; }
        public virtual Review Review { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
