//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShootNBunny
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ShootNBunnyEntities1 : DbContext
    {
        public ShootNBunnyEntities1()
            : base("name=ShootNBunnyEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Book> Book { get; set; }
        public virtual DbSet<BookGenre> BookGenre { get; set; }
        public virtual DbSet<Complaint> Complaint { get; set; }
        public virtual DbSet<ComplaintFreeze> ComplaintFreeze { get; set; }
        public virtual DbSet<Genre> Genre { get; set; }
        public virtual DbSet<Reading> Reading { get; set; }
        public virtual DbSet<ReadingStatus> ReadingStatus { get; set; }
        public virtual DbSet<Reason> Reason { get; set; }
        public virtual DbSet<Review> Review { get; set; }
        public virtual DbSet<RoleApplication> RoleApplication { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
